services:
  - type: web
    name: churn-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn --workers=1 --threads=2 --timeout=120 app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
